{% set name = "sunode" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 4
  script: "{{ PYTHON }} -m pip install . -vv"

  skip: True  # [py<3.7]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy >=1.14
    - liblapack
    - cffi
    - sundials >=5.3
  run:
    - python
    - numpy >=1.14
    - cffi
    - xarray
    - scipy
    - sundials >=5.3
    - numba >=0.49
    - typing_extensions
    - sympy

test:
  imports:
    - sunode
  requires:
    - pytest
    - hypothesis
    - statsmodels
  commands:
    - pytest --pyargs sunode

about:
  home: https://github.com/aseyboldt/sunode
  license: Apache-2.0
  license_family: Apache
  summary: A wrapper around sundials cvodes
