name: Python package

on: [push, pull_request]

jobs:
  test-on-linux:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 4
      matrix:
        operating-system: [ubuntu-latest]
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Install miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: sunode-dev
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,defaults
        channel-priority: strict
    - name: Install Dependences
      shell: bash -l {0}
      run: |
        conda install --yes conda-build conda-verify coverage pytest hypothesis statsmodels
    - name: Log conda
      shell: bash -l {0}
      run: |
        conda info
    - name: Build package
      shell: bash -l {0}
      run: |
        conda build --variants "{python: [${{ matrix.python-version }}]}" ./conda
    - name: Install package 
      shell: bash -l {0}
      run: |
        conda install --yes -c file:///usr/share/miniconda/envs/sunode-dev/conda-bld sunode
    - name: Test with coverage
      shell: bash -l {0}
      run: |
        coverage run -m pytest --pyargs sunode
  test-on-windows:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 4
      matrix:
        operating-system: [windows-latest]
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Install miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: sunode-dev
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,defaults
        channel-priority: strict
    - name: Log conda and Python versions
      shell: cmd /C call {0}
      run: |
        conda info
    - name: Install build and test dependencies
      shell: cmd /C call {0}
      run: |
        conda install conda-build conda-verify coverage pytest pytest-cov hypothesis statsmodels sundials
    - name: Sunode build
      shell: cmd /C call {0}
      run: |
        conda build --variants "{python: [${{ matrix.python-version }}]}" .\conda
    - name: Install sunode
      shell: cmd /C call {0}
      run: |
        conda install --yes -c local sunode
    - name: Run sunode tests
      shell: cmd /C call {0}
      run: |
        conda info
        pytest --cov=.\sunode --cov-report xml --cov-report term-missing sunode/
