name: Python package

on: [push, pull_request]

jobs:
  test-on-linux:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 4
      matrix:
        operating-system: [ubuntu-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependences
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        conda create -n sunode-env -q --yes -c conda-forge python=${PYVER} conda-build conda-verify coverage pytest hypothesis statsmodels
      env:
        PYVER: ${{ matrix.python-version }}
    - name: Install package 
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate sunode-env
        conda-build -c conda-forge ./conda
        conda install --yes -c file://${CONDA_PREFIX}/conda-bld/ -c conda-forge sunode
    - name: Test with coverage
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate sunode-env
        python -c "import sunode"
        coverage run -m pytest --pyargs sunode
  test-on-windows:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 4
      matrix:
        operating-system: [windows-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: sunode-dev
        python-version: 3.7
        channels: conda-forge,defaults
        channel-priority: strict
    - name: Log conda and Python versions
      run: |
        conda --version
        which python
        python --version
    - name: Download sundials
      run: git clone https://github.com/conda-forge/sundials-feedstock.git
    - name: Install build and test dependencies
      run: |
        conda install conda-build
    - name: Install build and test dependencies 2
      run: |
        conda install conda-verify
    - name: Install build and test dependencies 3
      run: |
        conda install coverage pytest pytest-cov
    - name: Install build and test dependencies 
      run: |
        conda install hypothesis statsmodels
    - name: Build sundials
      run: conda build .\sundials-feedstock\recipe
    - name: Build sunode
      run: |
        conda build -c local .\conda
    - name: Install sundials into the environment
      run: |
        conda install -c local sundials
    - name: Install sunode into the environment
      run: |
        conda install -c local sunode
    - name: Run sunode tests
      run: |
        pytest --cov=./sunode --cov-report xml --cov-report term-missing sunode/
