name: Python package

on: [push, pull_request]

jobs:
  run: 
    name: Linux Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 4
      matrix:
        operating-system: [ubuntu-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependences
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        conda create -n sunode-env -q --yes -c conda-forge python=${PYVER} conda-build conda-verify coverage pytest hypothesis statsmodels
      env:
        PYVER: ${{ matrix.python-version }}
    - name: Install package 
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate sunode-env
        conda-build -c conda-forge ./conda
        conda install --yes -c file://${CONDA_PREFIX}/conda-bld/ -c conda-forge sunode
    - name: Test with coverage
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate sunode-env
        python -c "import sunode"
        coverage run -m pytest --pyargs sunode
  run:
    name: Windows Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 4
      matrix:
        operating-system: [windows-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Install conda build dependences
      run: |
        conda install -c conda-forge conda-build conda-verify
    - name: Build sundials locally
      run: |
        git clone https://github.com/conda-forge/sundials-feedstock
        conda build -c conda-forge ./sundials-feedstock/recipe
    - name: Build sunode
      run: |
        conda build -c local -c conda-forge ./sunode/conda
    - name: Create environment to test installation
      run: |
        conda create -n sunode-env -c conda-forge python=${{ matrix.python-version }} coverage pytest pytest-cov hypothesis statsmodels
        activate sunode-dev
    - name: Install sundials into the environment
      run: |
        conda install -c local -c conda-forge sundials
    - name: Install sunode into the environment
      run: |
        conda install -c local -c conda-forge sunode
    - name: Run sunode tests
      run: |
        pytest --cov=./sunode --cov-report xml --cov-report term-missing sunode/
