name: Python package

on: [pull_request, push]

jobs:
  test-on-linux:
    runs-on: ${{ matrix.os }}
    name: sunode - ${{ matrix.os }} - ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
      with:
        path: "sunode"
    - name: Install miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: sunode-dev
        miniforge-version: latest
        python-version: ${{ matrix.python-version }}
    - name: Install Dependences
      run: |
        conda install --yes conda-build conda-verify coverage pytest hypothesis statsmodels aesara fd-find c-compiler
    - name: Debug paths
      run: |
        pwd
        fd libpython /
    - name: Build package
      run: |
        conda build --variants "{python: [${{ matrix.python-version }}]}" ./sunode/conda
    - name: Install package 
      run: |
        conda install --yes -c file:///${CONDA_PREFIX}/conda-bld/ sunode
    - name: Test with coverage
      run: |
        # conda activate doesn't seem to set paths to the conda prefix correctly
        env LD_LIBRARY_PATH=${CONDA_PREFIX}/lib coverage run -m pytest --pyargs sunode